# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3-rc-2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.0.11
maven_group=com.thecolonel63
archives_base_name=technomodel

# Fabric API
fabric_api_version=0.160.4+26.3